const ACCOUNT_KEY="ioEz_account";const ACCOUNTS_KEY="ioEz_accounts";
const $=id=>document.getElementById(id);
const accountButton=$("accountBtn"),accountPanel=$("accountPanel"),accountModal=$("accountModal"),accountForm=$("accountForm"),accountName=$("accountName"),accountEmail=$("accountEmail"),accountPassword=$("accountPassword"),accountTitle=$("accountTitle"),accountSubtitle=$("accountSubtitle"),accountSubmit=$("accountSubmit"),accountSwitch=$("accountSwitch"),accountMessage=$("accountMessage");
let accountMode="login";
function loadAccounts(){try{const x=JSON.parse(localStorage.getItem(ACCOUNTS_KEY)||"[]");return Array.isArray(x)?x:[]}catch{return[]}}
function saveAccounts(x){localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(x))}
function current(){try{return JSON.parse(localStorage.getItem(ACCOUNT_KEY)||"null")}catch{return null}}
function initials(name){return String(name||"ioEz").trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"IO"}
function msg(text,error=false){if(!accountMessage)return;accountMessage.textContent=text;accountMessage.className=`form-message ${error?"error":""}`}
function render(){const a=current();const avatar=$("accountAvatar"),large=$("accountAvatarLarge");if(a){const mark=initials(a.name);if($("accountIdentity"))$("accountIdentity").textContent=a.name;if($("accountIdentityLarge"))$("accountIdentityLarge").textContent=a.name;if($("accountEmailLabel"))$("accountEmailLabel").textContent=a.email||"";if(avatar)avatar.textContent=mark;if(large)large.textContent=mark;if($("accountModeLabel"))$("accountModeLabel").textContent="Cuenta activa";accountButton?.classList.add("signed-in")}else{if($("accountIdentity"))$("accountIdentity").textContent="Invitado";if($("accountIdentityLarge"))$("accountIdentityLarge").textContent="Invitado";if($("accountEmailLabel"))$("accountEmailLabel").textContent="Sin cuenta";if(avatar)avatar.textContent="✦";if(large)large.textContent="✦";if($("accountModeLabel"))$("accountModeLabel").textContent="Cuenta local";accountButton?.classList.remove("signed-in")}}
function open(mode="login"){accountMode=mode;accountTitle.textContent=mode==="login"?"Iniciar sesión":"Crear cuenta";accountSubtitle.textContent=mode==="login"?"Vuelve a tu espacio de ioEz.":"Crea tu perfil para este navegador.";accountSubmit.textContent=mode==="login"?"Entrar":"Crear cuenta";accountSwitch.textContent=mode==="login"?"Crear una cuenta":"Ya tengo una cuenta";accountName.parentElement.style.display=mode==="login"?"none":"flex";accountPassword.value="";msg("");accountModal?.classList.remove("hidden");accountPanel?.classList.add("hidden");setTimeout(()=>{(mode==="login"?accountEmail:accountName)?.focus()},60)}
accountButton?.addEventListener("click",()=>{render();accountPanel?.classList.toggle("hidden")});$("accountLogin")?.addEventListener("click",()=>open("login"));$("accountRegister")?.addEventListener("click",()=>open("register"));accountSwitch?.addEventListener("click",()=>open(accountMode==="login"?"register":"login"));$("closeAccount")?.addEventListener("click",()=>accountPanel?.classList.add("hidden"));$("closeAccountModal")?.addEventListener("click",()=>accountModal?.classList.add("hidden"));accountModal?.addEventListener("click",e=>{if(e.target===accountModal)accountModal.classList.add("hidden")});$("logoutAccount")?.addEventListener("click",()=>{localStorage.removeItem(ACCOUNT_KEY);render();accountPanel?.classList.add("hidden")});
accountForm?.addEventListener("submit",e=>{e.preventDefault();const email=accountEmail.value.trim().toLowerCase(),password=accountPassword.value,name=accountName.value.trim();if(!email||!password||(accountMode==="register"&&!name))return msg("Completa todos los campos.",true);if(!/^\S+@\S+\.\S+$/.test(email))return msg("Escribe un correo válido.",true);if(password.length<6)return msg("La contraseña debe tener al menos 6 caracteres.",true);const accounts=loadAccounts();if(accountMode==="register"){if(accounts.some(a=>a.email===email))return msg("Ya existe una cuenta con ese correo.",true);accounts.push({name,email,password,createdAt:new Date().toISOString()});saveAccounts(accounts);localStorage.setItem(ACCOUNT_KEY,JSON.stringify({name,email}));msg("Cuenta creada. Bienvenido a ioEz.")}else{const a=accounts.find(x=>x.email===email&&x.password===password);if(!a)return msg("Correo o contraseña incorrectos.",true);localStorage.setItem(ACCOUNT_KEY,JSON.stringify({name:a.name,email:a.email}));msg("Sesión iniciada.")}render();setTimeout(()=>accountModal?.classList.add("hidden"),450)});
render();