const $=s=>document.querySelector(s);const db=JSON.parse(localStorage.getItem("oeios-users")||"{}");let mode="login",current="";
function setMode(m){mode=m;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.mode===m));$("#emailBox").classList.toggle("hide",m==="login");$("#email").required=m==="register";$("#message").textContent=""}
document.querySelectorAll(".tab").forEach(x=>x.onclick=()=>setMode(x.dataset.mode));
$("#form").onsubmit=e=>{e.preventDefault();const u=$("#user").value.trim(),p=$("#pass").value;if(mode==="register"){if(db[u])return $("#message").textContent="Ese usuario ya existe.";db[u]={email:$("#email").value,pass:p,name:u,bg:"#050505",accent:"#ffffff"};localStorage.setItem("oeios-users",JSON.stringify(db))}else if(!db[u]||db[u].pass!==p)return $("#message").textContent="Usuario o contraseña incorrectos.";current=u;openSystem()};
function openSystem(){const a=db[current];$("#auth").classList.add("hide");$("#system").classList.remove("hide");$("#hello").textContent=a.name;$("#displayName").value=a.name;$("#accent").value=a.accent||"#fff";setBg(a.bg||"#050505")}
function setBg(c){$("#phone").style.background=c;document.querySelectorAll(".palette button").forEach(b=>b.style.outline=b.dataset.bg===c?"2px solid white":"none")}
document.querySelectorAll(".palette button").forEach(b=>b.onclick=()=>setBg(b.dataset.bg));$("#accent").oninput=e=>$("#phone").style.borderColor=e.target.value+"66";
$("#save").onclick=()=>{const a=db[current];a.name=$("#displayName").value.trim()||current;a.accent=$("#accent").value;a.bg=$("#phone").style.background;db[current]=a;localStorage.setItem("oeios-users",JSON.stringify(db));$("#hello").textContent=a.name;$("#saved").textContent="Cambios guardados ✓"};
$("#exit").onclick=()=>{current="";$("#system").classList.add("hide");$("#auth").classList.remove("hide");$("#form").reset();setMode("login")};
function clock(){const d=new Date(),t=d.toLocaleTimeString("es-PR",{hour:"2-digit",minute:"2-digit"});$("#clock").textContent=t;$("#bigClock").textContent=t;$("#today").textContent=d.toLocaleDateString("es-PR",{weekday:"long",day:"numeric",month:"long"}).replace(/^./,x=>x.toUpperCase())}clock();setInterval(clock,1000);setMode("login");